DROP TABLE IF EXISTS userRole;
DROP TABLE IF EXISTS users;

CREATE TABLE usertype( id INT AUTO_INCREMENT  PRIMARY KEY,
 typename VARCHAR(250) NOT NULL,
);


CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  typeid INT NOT NULL,
  creationDate DATE DEFAULT CURRENT_TIMESTAMP ,
  
 FOREIGN KEY (typeid) REFERENCES usertype
);


CREATE TABLE RETAIL_ITEM_TYPE ( id INT AUTO_INCREMENT  PRIMARY KEY,
 typename VARCHAR(250) NOT NULL,
 discountapplicable VARCHAR(1) NOT NULL
);

CREATE TABLE Item (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
  	typeid INT NOT NULL,
  	price DECIMAL NOT NULL,
  	
  	FOREIGN KEY (typeid) REFERENCES RETAIL_ITEM_TYPE
);

CREATE TABLE Discount (
	id INT AUTO_INCREMENT PRIMARY KEY,
	discount_percentage INT NOT NULL,
	usertypeid INT NOT NULL,
	
	FOREIGN KEY (usertypeid) REFERENCES usertype
);

CREATE TABLE Bill (
	id INT AUTO_INCREMENT PRIMARY KEY,
	userid INT NOT NULL,
	Amount DECIMAL NOT NULL,
	DiscountApplicable VARCHAR(1) NOT NULL,
	
	FOREIGN KEY (userid) REFERENCES users
	);

CREATE TABLE Bill_Items(
	id INT AUTO_INCREMENT PRIMARY KEY,
	billid DECIMAL NOT NULL,
	itemId DECIMAL NOT NULL,
	quantity DECIMAL NOT NULL,
	
	FOREIGN KEY (billid) REFERENCES Bill,
	FOREIGN KEY (itemId) REFERENCES Item
	
);












